### PR TITLE
add newline to (import-notify) message in compile.ss

### PR DESCRIPTION
**Pull request by owaddell**

### CODE REVIEW

**Comment by burgerrg** [comment]
It might be useful to add a mat to 8.ms for this.

**Comment by burgerrg** [comment]
I didn't see any others missing in compile.ss.

On a related note, it seems that the code base uses `~%` and `\n` for newlines. I think the latter is slightly more efficient. You might consider changing all the `~%` to `\n` in compile.ss for consistency.

**Comment by dybvig** [comment]
It shouldn't actually matter since the format-string compiler is designed to produce the same code for `~%` and `\n` in direct calls to `printf`, `fprintf`, `format`, `errorf`, etc.

**Comment by burgerrg** [comment]
I don't think adding a mat for the import-notify "reading ..." message is worthwhile. We checked syntax.ss also and didn't find any other missing newlines.

**Pull request merged**
