### PR TITLE
Change collector to promote objects only one generation at a time

### PR DESCRIPTION
**Pull request by dybvig**
This pull request addresses issue #513.  See LOG for detailed changes.

It also changes the x86 assembler to maintain 16-byte stack alignment (if incoming frames are 16-byte aligned) because newer versions of gcc count on 16-bit alignment for some generated sse instructions.  This properly belongs in a different pull request, but I discovered the alignment problem while testing the gc changes and I also didn't want to have to push two sets of boot files.

### CODE REVIEW

**Comment by dybvig** [comment]
@burgerrg, I added you as a reviewer since I'm hoping you'll try building this on Windows.

**Comment by burgerrg** [comment]
The following compiler error is raised on Linux:

**Comment by burgerrg** [comment]
The following compiler error is raised on Windows:
```
gcwrapper.c(789): error C2065: 'S_child_processes': undeclared identifier
gcwrapper.c(789): error C2109: subscript requires array or pointer type
```

**Comment by dybvig** [comment]
Thanks!  The gcwrapper.c problem on Windows is because I forgot to wrap the assignment in an "#ifndef Windows".

The gc.c problem on Linux is concerning.  By my reading of the code, there's no path to the reference to __to_g that doesn't assign __to_g first.  If I'm correct, this means the C compiler is issuing a bogus warning, possibly because it is using something other than live analysis to identify uninitialized values, because it's live analysis is broken, or because the code produced prior to live analysis is broken.  The version of gcc (10.1.1) on my machine doesn't complain.

**Comment by burgerrg** [comment]
The Travis CI service provides Ubuntu 18.04, which has gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 installed.

**Comment by burgerrg** [comment]
Initializing __to_g to 0 (although it shouldn't be necessary) resolves the error on Ubuntu 18.04, and the rest of the system compiles without warnings.

**Comment by burgerrg** [comment]
The Windows build failed with `gcwrapper.obj : error LNK2019: unresolved external symbol S_gc_011 referenced in function S_do_gc`

**Comment by burgerrg** [comment]
I'll update the c/Makefile.* files and commit to this pull request.

**Comment by burgerrg** [comment]
The automated tests all pass now!

**Pull request merged**
