### PR TITLE
Add support for building with Visual Studio BuildTools

### PR DESCRIPTION
**Pull request by kleinpa**
I've been trying to build and run Chez in a container so support for Visual Studio BuildTools would be nice.

I have not yet successfully used VS's BuildTools to produce a build that passes all the mats and I'd be happy to sit on this PR until I can prove it all works.

Current mat summary: https://gist.github.com/kleinpa/84f535942dc370846774e38bbf17328a

### CODE REVIEW

**Comment by burgerrg** [comment]
Thanks, Peter! Would you please add a line to LOG indicating that you changed c/vs.bat, and squash the 2 commits into one?

**Comment by burgerrg** [comment]
Some of the mat failures are because you don't have iconv.dll in the bin/%m folder. I use https://github.com/win-iconv/win-iconv to build one for i3nt and a6nt.

**Comment by burgerrg** [comment]
The directory-list failures with ~ depend on code in c/io.c. It uses HOMEDRIVE and HOMEPATH. Perhaps that code should use USERPROFILE instead?

**Comment by burgerrg** [comment]
I installed Visual Studio 2017 BuildTools, and the a6nt machine passed the mats (o=0 and o=3).

**Comment by kleinpa** [comment]
Squashing on the pull request branch caused some confusion but should be good to go.

**Pull request merged**
