### PR TITLE
Support for 64-bit RISC-V and LoongArch

### PR DESCRIPTION
**Pull request by maoif**
This PR adds support for riscv64 and loongarch64 architectures.
Only 64-bit Linux is supported right now.

RISC-V is the popular free and open-source ISA.
The current backend uses the G extension (M, A, F, D and Zifencei).

LoongArch is a new ISA developed by a Chinese company and is similar to RISC-V.

The machine names for the two architectures are `[t]rv64le` and `[t]la64le`.

I thank @mflatt for completing the FFI code when he merged the RISC-V code into Racket.
The two backends' FFI do not support varargs yet.

## Representation of `+nan.0`

There was one error (as noted [here](https://github.com/cisco/ChezScheme/issues/700)) that was
related to the different representations of `+nan.0` on different archs.

`(fl/ 0.0 0.0)` gives `+nan.0` on all archs. But on x86_64, the hex representation of the result
is `0xfff8000000000000`, yet on RISC-V and LoongArch the result is `0x7ff8000000000000`.

Both are correct. `0xfff8000000000000` is x86_64's QNaN Floating-Point Indefinite
(Intel® 64 and IA-32 Architectures Software Developer’s Manual, Vol. 1, 4-17)
and `0x7ff8000000000000` is the ordinary QNaN.

So it is not recommended to make the `[t]rv64le` and `[t]la64le` boot files on x86_64
because x86_64's QNaN will be baked into the boot file, which would lead to wrong
results on RISC-V and LoongArch in code like `(eqv? (fl/ 0.0 0.0) +nan.0)` (which should be `#t`).
Here `(fl/ 0.0 0.0)` will be computed by the instructions and give `0x7ff8000000000000`,
and `+nan.0` will be the baked-in (wrong) value of `0xfff8000000000000`.

## Test result

Ever since the RISC-V port was just bootstrapped, there were lots of errors whenthe tests were run. I tried hard to eliminate most of them. Some of them are duenot to the wrong code in the port, as detailed below.

### Test environemnt

The RISC-V backend is tested on qemu 8.0.2 and on a Sifive Unmatched.

The LoongArch backend is tested only on qemu 8.0.2 because, well, I don't have access to a LoongArch
machine.

### Tests that are influenced by the speed of execution

Since nowadays these two types of processors are not so fast, andsome tests are (I think) influenced by the speed of execution, soI bypassed them. They include:

- A `(current-time)` test in `5_1.ms`
- A cost-center test `mics.ms`

### One last probablistic error

There's still one error that sometimes appears and sometimes does not.

For RISC-V, the errors are:

```
> foreign.mo:Bug in mat foreign-ftype clause 76 at line 1921, char 3 of ../foreign.ms
> 5_8.mo:Bug in mat box-cas! clause 4 at line 41, char 3 of ../5_8.ms
> 5_6.mo:Bug in mat vector-cas! clause 4 at line 1265, char 3 of ../5_6.ms
```

For LoongArch, the error is:

```
> 5_6.mo:Bug in mat vector-cas! clause 4 at line 1265, char 3 of ../5_6.ms
```

The reason I call them *one* error is because they all have to do with atomics.
Specifically, the `foreign.mo` error compiles to `asm-lock`, and the `5_8.mo` and `5_6.mo` errors compile to `asm-cas`.
Both asm templates use the `lr.d` (load-reserved) and `sc.d` (store-conditional) instructions.

If I enter the respective test code directly in REPL, everything's fine.
Please help check if there's anything wrong with the backend.

### CODE REVIEW

**Comment by maoif** [comment]
Anyone give me some feedback? 😅

**Comment by cjfrisz** [comment]
Thanks for the PR! It will take some time to review the commits, though I know it was merged for Racket, which could help on this end.

We may also need to have a discussion about how to test these backends. Typically, whether it’s possible to run CI for a target determines whether it’s officially or unofficially supported.

**Comment by mflatt** [comment]
The RISC-V half here (as authored by @maoif) is included in v9.9.9 merge 47daa9b34016de84fd111801d9d589d15a523abe.

**Comment by burgerrg** [comment]
Please open a separate pull request if you'd like to add support for LoongArch.

**Comment by maoif** [comment]
> Please open a separate pull request if you'd like to add support for LoongArch.

Sure, I'll be preparing for that.

**Pull request closed without merging**
