### PR TITLE
Autoconfig, detect if X11 exist on Mac OS X

### LINKED ISSUE #325: X11 path issue on Mac OS X 10.13
https://github.com/cisco/ChezScheme/blob/6c738bdfde601b815c296f489697e61c314e4621/c/Mf-a6osx#L20

Actually it is in `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/Tk.framework/Headers/`, there is not a symbol link from `/opt/include/X11`. See https://support.apple.com/en-us/ht201341

### PR DESCRIPTION
**Pull request by tison1**
This will close #325 

The main issue is that on current OS X, X11 is no more provided default.

### CODE REVIEW

**Comment by tison1** [comment]
cc @burgerrg

**Comment by burgerrg** [comment]
If we make this change, then on non-X11 macOS systems, Chez Scheme's expression editor won't have pasteboard support. @akeep and I would prefer to see a change that supports the pasteboard even when X11 is not installed.

**Comment by tison1** [comment]
@burgerrg thanks for the comment, then I will close this PR and take a try to implement as your comment later.

**Comment by burgerrg** [comment]
Thanks, it would be great if you could unentangle the X11 clipboard and macOS pasteboard in the expression editor.

**Comment by akeep** [comment]
I did that in check in: f8cf536720fe43d07ca83d284e5bd1733c97372a So I think
we're good there, the only missing part was the X11 autodetect.

-andy:)



On July 17, 2018 at 10:16:50 AM, Bob Burger (notifications@github.com)
wrote:

Thanks, it would be great if you could unentangle the X11 clipboard and
macOS pasteboard in the expression editor.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/cisco/ChezScheme/pull/333#issuecomment-405597704>, or mute
the thread

**Comment by tison1** [comment]
@akeep I check the commit, it seems we can reopen this pr and merge it, and then things go well, doesn't it?

**Comment by burgerrg** [comment]
Thanks, @akeep!

**Comment by burgerrg** [comment]
@tison1, thank you for this pull request!

**Pull request merged**
