### PR TITLE
heed app-convention to fix apply issue

### PR DESCRIPTION
**Pull request by owaddell**
Sketch of a fix for #389 

Is there any point in trying `#2%apply` in `fold-primref2` when `app-convention` is not `call`? Seems that if `objs-if-constant` succeeds here, but the `apply` handler didn't turn `apply` into `call`, then we're going to end up residualizing anyway, so I'm inclined to check the convention earlier in that first `cond` clause and simplify.

- [x] get review from someone who has been in this code more recently
- [x] do we need more tests?
- [x] update LOG

### CODE REVIEW

**Comment by owaddell** [comment]
Thanks. I've updated my branch to add some tests and to bail earlier if `app-convention` is not `call`.

I may be bailing too early, since inline handlers won't be able to special-case based on `app-convention`. Offhand, I'm not sure who would want to do that (maybe to avoid a value-visit somewhere?).

Travis will be unhappy since I haven't yet updated the expected errors.

**Comment by owaddell** [comment]
Attempted to update expected errors and restored original indentation to minimize diffs from master.

**Comment by owaddell** [comment]
Added a test for the 'effect unrestricted discard case, updated LOG, and squashed.

**Comment by owaddell** [comment]
Re-pushed to update the release notes.

**Comment by dybvig** [comment]
Thanks for the fix!

**Pull request merged**
