### PR TITLE
x86-64 fasl relocator: Use single 7-byte NOP after direct calls/jumps

### PR DESCRIPTION
**Pull request by fweimer**
See issue #539 for background.

`a6le/mats/summary` is still clean after this change.

### CODE REVIEW

**Comment by dybvig** [comment]
I'm curious how this affects performance.  I assume it should reduce overall instruction decoding time, though such assumptions don't always hold.  Have you verified that it at least doesn't make code run slower?  If so, it looks like a great change.  Please add a LOG entry.

**Comment by fweimer** [comment]
Fair enough. What would be an acceptable benchmark? I usually measure instruction counts because they are more stable than timings, but that would be cheating in this case.

The 7-byte NOP sequence is recommended in both the AMD and Intel programming manuals. Perhaps this is good enough?

**Comment by dybvig** [comment]
Okay, I just ran a set of benchmarks on my mac laptop.  The average difference wasn't significant, so let's go ahead.  I'll pull the change once you add the LOG entry.

**Comment by fweimer** [comment]
Fair enough. I added:

```
- use a 7-byte NOP in the x86_64 fasl relocator instead of 7 1-byte NOPs
```

**Comment by dybvig** [comment]
Please add the file modified (fasl.c) in the LOG entry following the format of the earlier entries.  It might seem unnecessary given that we have the git log, but Chez Scheme tends to outlast revision control systems.

**Comment by dybvig** [comment]
Also you'll have to rebase (and squash, please) since I've just pulled another request that modified LOG.

**Pull request merged**
