### PR TITLE
x86_64: fix foreign-procedure `&` results that are not a multiple of a word

### PR DESCRIPTION
**Pull request by mflatt**
This is a repair for the main bug report in #320.

I have not yet run the updated tests on ppc32le, but I'll do that tomorrow.

### CODE REVIEW

**Comment by burgerrg** [comment]
Thanks for the fix! The changes for `malloc_at_boundary` don't `mprotect` the second page. I think that's important to be able to detect this problem. Use `VirtualProtect(p + si.dwPageSize, si.dwPageSize, PAGE_NOACCESS, &dummy)` in Windows.

**Comment by burgerrg** [comment]
```
EXPORT void *malloc_at_boundary(int sz)
{
  SYSTEM_INFO si;
  char *p;
  DWORD dummy;
  GetSystemInfo(&si);
  p = VirtualAlloc(NULL, si.dwPageSize, MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
  VirtualProtect(p + si.dwPageSize, si.dwPageSize, PAGE_NOACCESS, &dummy);
  return p + si.dwPageSize - sz;
}
```

**Comment by mflatt** [comment]
@burgerrg Ok, I'll make that improvement (but allocating two pages before adjusting the second one). The main problem wasn't so much being unlucky with the next page, though, but that the return-argument tests weren't using `malloc_at_boundary` before.

**Comment by burgerrg** [comment]
Thanks, that makes sense.

**Comment by mflatt** [comment]
The "foreign.ms" tests pass on ppc32le, and `malloc_on_boundary` is updated for Windows, so I think this is ready for review.

**Comment by burgerrg** [comment]
Thanks again for this fix!

**Pull request merged**
