### PR TITLE
added unicode support to windows console i/o

### PR DESCRIPTION
**Pull request by NHALX**
Fixes issue #484. 

Please note the comment regarding SetConsoleCtrlHandler in os_read.

### CODE REVIEW

**Comment by burgerrg** [comment]
Thank you for figuring out how to get Unicode BMP console I/O in Windows! I read on one of Microsoft's blogs that the console currently supports 16-bit Unicode characters only (no surrogates) but that they plan to add support for this in a future update. In the meantime, what we have seems to work.

**Comment by burgerrg** [comment]
Please look at my proposed simplifications in https://github.com/cisco/ChezScheme/tree/unicode. Sometimes when I pressed CTRL-C at the repl with --eedisable, it would print two prompts as though CTRL-C were pressed twice. I think this is acceptable.

**Comment by NHALX** [comment]
@burgerrg on a threaded build, when --eedisable is enabled, CTRL-C hangs with your changes. I had the same problem in one of the previous versions of my patch, and there is a comment about it in the os_read function. I'm not sure what was causing it, but after some refactoring it went away.

**Comment by burgerrg** [comment]
Thank you, I'll investigate why refactoring changes the CTRL-C behavior. There must be a race somewhere.

**Comment by burgerrg** [comment]
The MSDN description of [HandlerRoutine](https://docs.microsoft.com/en-us/windows/console/handlerroutine) explains the race. When CTRL-C is pressed, the handler routine is run in a new thread. I think this causes a bad interaction with our handler and the ReadConsoleW call in new-io.c. I'm investigating it.

**Comment by burgerrg** [comment]
I found that by sleeping for 1 ms when ReadConsoleW returns EINTR before re-enabling the ConsoleCtrlHandler, we don't get the spurious double CTRL-C.

Then I found that threaded Chez Scheme does not handle console input and keyboard interrupts on any platform because the thread-safe handler uses the with-tc-mutex macro that disables interrupts, which makes the call to $event in io.ss not process the keyboard interrupt. On Windows, I handle this case by calling S_noncontinuable_interrupt, which is what happens on other platforms when you press CTRL-C the second time.

See if this works for you.

**Comment by burgerrg** [comment]
I entered issue https://github.com/cisco/ChezScheme/issues/492 for the CTRL-C trouble on threaded Unix-like versions.

**Comment by burgerrg** [comment]
@NHALX I got CTRL-C working reliably in threaded and non-threaded Windows builds. See what you think of the [changes](https://github.com/cisco/ChezScheme/compare/master...unicode).

**Comment by NHALX** [comment]
@Burgerrg would it be better to use SetConsoleMode and toggle the ENABLE_PROCESSED_INPUT flag instead of dealing with signal handler masks the current way? Presumably this would bypass any races, which would be preferable to trying to win/lose them with Sleep.

My workstation is being repaired so I will need to wait a few days to test anything.

**Comment by burgerrg** [comment]
No, we want processed input so that the line is editable. I believe I'm using the APIs correctly and there shouldn't be a race, but apparently there is. I'm OK with a small sleep in the CTRL-C case only. We do similar things to deal with Windows' DeleteFile returning before the file is actually deleted.

**Comment by NHALX** [comment]
@burgerrg Sorry for the delay. The code seems to work fine here.

**Comment by burgerrg** [comment]
The Windows Travis-CI build was failing because the building of mat output left it waiting for console input. I finally reproduced the behavior in my Windows VM and am now trying to debug it.

**Comment by burgerrg** [comment]
Thanks again for your work on this!

**Pull request merged**
